import Head from "next/head";
import Image from "next/image";
import { Card } from "antd";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Upzyde Form Dashboard</h1>

        <div className={styles.grid}>
          <div className="site-card-border-less-wrapper">
            <Card
              bordered={false}
              style={{
                width: 300,
              }}
            >
              <h2>Newsletter Form &rarr;</h2>
            </Card>
          </div>
          <div className="site-card-border-less-wrapper">
            <Card
              bordered={false}
              style={{
                width: 300,
              }}
            >
              <h2>Request Demo Form &rarr;</h2>
            </Card>
          </div>
          <div className="site-card-border-less-wrapper">
            <Card
              bordered={false}
              style={{
                width: 300,
              }}
            >
              <h2>Increase Revenue Form &rarr;</h2>
            </Card>
          </div>

          <div className="site-card-border-less-wrapper">
            <Card
              bordered={false}
              style={{
                width: 300,
              }}
            >
              <Link href="/contact-form">
                <h2>Contact Us Form &rarr;</h2>
              </Link>
            </Card>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
