import Head from "next/head";
import Image from "next/image";
import { Card } from "antd";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Layout from "../models/components/Layout/layout";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className={styles.title}>Upzyde Dashboard</h1>

        <div className={styles.grid}>
          <div className="site-card-border-less-wrapper">
            <Card
              bordered={false}
              style={{
                width: 300,
              }}
            >
              <h2>Newsletter Form &rarr;</h2>
            </Card>
          </div>
          <div className="site-card-border-less-wrapper">
            <Card
              bordered={false}
              style={{
                width: 300,
              }}
            >
              <h2>Request Demo Form &rarr;</h2>
            </Card>
          </div>
          <div className="site-card-border-less-wrapper">
            <Card
              bordered={false}
              style={{
                width: 300,
              }}
            >
              <h2>Increase Revenue Form &rarr;</h2>
            </Card>
          </div>

          <div className="site-card-border-less-wrapper">
            <Card
              bordered={false}
              style={{
                width: 300,
              }}
            >
              <Link href="/contact-form">
                <h2>Contact Us Form &rarr;</h2>
              </Link>
            </Card>
          </div>
        </div>
      </div>
    </Layout>
  );
}
